# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: npm i

      # Runs a single command using the runners shell
      - name: Nrwl Nx
        # You may pin to the exact commit or the version.
        # uses: MansaGroup/nrwl-nx-action@96194697f74d2e33cb02dbb3ee1dc3eab1f97bd1
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          # Comma-separated list of targets to execute
          targets: build
          # Comma-separated list of projects to use
          projects: # optional
          # Run the targets on all projects
          all: # optional, default is false
          # Use the Nx' affected subcommand to only process affected projects
          affected: # optional, default is true
          # Run the tasks in parallel (can be expensive)
          parallel: # optional, default is false
          # Number of tasks to execute in parallel (can be expensive)
          maxParallel: # optional, default is 3
          # Optional arguments to append to the Nx command
          args: # optional, default is 
          # Enable support for Nx Cloud
          nxCloud: # optional, default is false
          # Path to the Nx workspace, needed if not the repository root
          workingDirectory: # optional
